AppLogin/AppLogin/Areas/RH/Models/Funcionario.cs
using MySql.Data.MySqlClient;
using RestauranteMexicano.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace RestauranteMexicano.Areas.RH.Models
{
    public class Funcionario
    {
        public DefaultConnectionDB db = new DefaultConnectionDB();

        /* TABELA
        
            id int AI PK 
            funcionario varchar(30) 
            cpf varchar(15) 
            dataNascimento date 
            sexo varchar(20) 
            idFuncionario int
        */

        // Atributos

        [Key]
        [Display(Name = "Id")]
        public int id { get; set; }

        [Required]
        [Display(Name = "Nome")]
        [StringLength(30, ErrorMessage = "O limite é de 30 caracteres.")]
        public String nome { get; set; }

        [Required]
        [Display(Name = "CPF")]
        [StringLength(15, ErrorMessage = "O limite é de 15 caracteres.")]
        public String cpf { get; set; }

        [Required]
        [Display(Name = "Data de nascimento")]
        public DateTime dataNascimento { get; set; }

        [Display(Name = "Sexo")]
        [StringLength(15, ErrorMessage = "O limite é de 15 caracteres.")]
        public String sexo { get; set; }

        [Required]
        [Display(Name = "Id cargo")]
        public int idCargo { get; set; }
        public virtual Cargo cargo { get; set; }


        // Métodos

        public void InsertFuncionario(Funcionario funcionario)
        {
            string strQuery = string.Format("insert into Funcionario(id, funcionario, cpf, dataNascimento, sexo, idCargo) " +
                                         "values ({0},'{1}','{2}','{3}','{4}',{5});", funcionario.id, funcionario.nome, funcionario.cpf, funcionario.dataNascimento.ToString("yyyy-MM-dd"), funcionario.sexo, funcionario.idCargo);

            db.ExecutaComando(strQuery);
        }

        public List<Funcionario> SelectFuncionario()
        {
            string StrQuery = "select * from Funcionario;";
            MySqlDataReader myReader = db.RetornaRegistro(StrQuery);
            var ListaFuncionario = new List<Funcionario>();

            while (myReader.Read())
            {
                var objFuncionario = new Funcionario()
                {
                    id = int.Parse(myReader["id"].ToString()),
                    nome = myReader["funcionario"].ToString(),
                    cpf = myReader["cpf"].ToString(),
                    dataNascimento = DateTime.Parse(myReader["dataNascimento"].ToString()),
                    sexo = myReader["sexo"].ToString(),
                    idCargo = int.Parse(myReader["idCargo"].ToString())
                };
                ListaFuncionario.Add(objFuncionario);
            }
            myReader.Close();
            return ListaFuncionario;
        }

        public void DeleteFuncionario(Funcionario funcionario)
        {
            string StrQuery = string.Format("delete from Funcionario where id = {0};", funcionario.id);
            db.ExecutaComando(StrQuery);
        }

        public Funcionario SelectIdFuncionario(Funcionario funcionario)
        {
            string StrQuery = string.Format("select * from Funcionario where id = {0};", funcionario.id);
            MySqlDataReader myReader = db.RetornaRegistro(StrQuery);

            var objFuncionario = new Funcionario();

            while (myReader.Read())
            {
                objFuncionario.id = int.Parse(myReader["id"].ToString());
                objFuncionario.nome = myReader["funcionario"].ToString();
                objFuncionario.cpf = myReader["cpf"].ToString();
                objFuncionario.dataNascimento = DateTime.Parse(myReader["dataNascimento"].ToString());
                objFuncionario.sexo = myReader["sexo"].ToString();
                objFuncionario.idCargo = int.Parse(myReader["idCargo"].ToString());
            }
            myReader.Close();
            return objFuncionario;
        }

        public void UpdateFuncionario(Funcionario funcionario)
        {
            string StrQuery = "";
            StrQuery += "update Funcionario set ";
            StrQuery += string.Format("funcionario = '{0}', ", funcionario.nome);
            StrQuery += string.Format("cpf = '{0}', ", funcionario.cpf);
            StrQuery += string.Format("dataNascimento = '{0}', ", funcionario.dataNascimento.ToString("yyyy-MM-dd"));
            StrQuery += string.Format("sexo = '{0}', ", funcionario.sexo);
            StrQuery += string.Format("idCargo = {0} ", funcionario.idCargo);
            StrQuery += string.Format("where id = {0};", funcionario.id);

            db.ExecutaComando(StrQuery);
        }
    }
}

AppLogin/AppLogin/Areas/RH/Controllers/FuncionarioController.cs
using RestauranteMexicano.Areas.RH.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RestauranteMexicano.Areas.RH.Controllers
{
    public class FuncionarioController : Controller
    {
        // GET: RH/Funcionario
        public ActionResult Index()
        {
            var objFuncionario = new Funcionario();
            var ListaFuncionario = objFuncionario.SelectFuncionario();
            return View(ListaFuncionario);
        }

        public ActionResult Details(int id)
        {
            Funcionario funcionario = new Funcionario() { id = id };
            var objFuncionario = new Funcionario();
            funcionario = objFuncionario.SelectIdFuncionario(funcionario);
            return View(funcionario);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Funcionario funcionario)
        {
            if (ModelState.IsValid)
            {
                var objFuncionario = new Funcionario();
                objFuncionario.InsertFuncionario(funcionario);
                return RedirectToAction("Index");
            }
            return View(funcionario);
        }

        public ActionResult Edit(int id)
        {
            var funcionario = new Funcionario() { id = id };
            var objFuncionario = new Funcionario();
            funcionario = objFuncionario.SelectIdFuncionario(funcionario);
            return View(funcionario);
        }

        [HttpPost]
        public ActionResult Edit(Funcionario funcionario)
        {
            if (ModelState.IsValid)
            {
                var objFuncionario = new Funcionario();
                objFuncionario.UpdateFuncionario(funcionario);
                return RedirectToAction("Index");
            }
            return View(funcionario);
        }

        public ActionResult Delete(int id)
        {
            var funcionario = new Funcionario() { id = id };
            var objFuncionario = new Funcionario();
            funcionario = objFuncionario.SelectIdFuncionario(funcionario);
            return View(funcionario);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirma(int id)
        {
            var funcionario = new Funcionario() { id = id };
            var objFuncionario = new Funcionario();
            objFuncionario.DeleteFuncionario(funcionario);
            return RedirectToAction("index");
        }
    }
}

AppLogin/AppLogin/Areas/RH/Views/Funcionario/Create.cshtml
@model RestauranteMexicano.Areas.RH.Models.Funcionario

@{
    ViewBag.Title = "Cadastrar Funcionários";
}
<div class="animated animatedFadeInUp fadeInUp">
    <div class="tabela">
        <br>
        <div class="primeira">
            <!-- <a href='https://www.freepik.com/vectors/food'>Food vector created by freepik - www.freepik.com</a> -->
            <img src="~/Content/imagens/chef.jpg" width="100%" height="100%" />
        </div>
        <div class="segunda">
            @using (Html.BeginForm())
            {

                @Html.AntiForgeryToken()


                @Html.LabelFor(model => model.nome, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.nome, new { htmlAttributes = new { @class = "form-control" } })

                @Html.LabelFor(model => model.cpf, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.cpf, new { htmlAttributes = new { @class = "form-control" } })

                @Html.LabelFor(model => model.dataNascimento, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.dataNascimento, new { htmlAttributes = new { @class = "form-control" } })



                @Html.LabelFor(model => model.sexo, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.sexo, new { htmlAttributes = new { @class = "form-control" } })

                @Html.LabelFor(model => model.idCargo, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.idCargo, new { htmlAttributes = new { @class = "form-control" } })


                <input type="submit" value="Cadastrar" class="button" function/>

                @Html.ActionLink("Visualizar todos", "Index")

                @section Scripts {
                    @Scripts.Render("~/bundles/jqueryval")
                }

            }
        </div>
    </div>
</div>

AppLogin/AppLogin/Areas/RH/Views/Funcionario/Delete.cshtml
@model RestauranteMexicano.Areas.RH.Models.Funcionario

@{
    ViewBag.Title = "Delete";
}

<div class="animated animatedFadeInUp fadeInUp">
    <div class="tabela">
        <br>
        <div class="primeira">
            <img src="~/Content/imagens/delete-confirmation.png" width="100%" height="100%"/>
        </div>
        <div class="segunda">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <h3> Você realmente deseja deletar esse registro? </h3>
                <br/>
                <input type="submit" value="Deletar" class="button" />

                @Html.ActionLink("Voltar", "Index")
            }
        </div>
    </div>
</div>

AppLogin/AppLogin/Areas/RH/Views/Funcionario/Details.cshtml
@model RestauranteMexicano.Areas.RH.Models.Funcionario

@{
    ViewBag.Title = "Details";
}

<div class="animated animatedFadeInUp fadeInUp">
    <div class="tabela">
        <br>
        <div class="primeira">
            <!-- <a href='https://www.freepik.com/vectors/food'>Food vector created by freepik - www.freepik.com</a> -->
            <img src="~/Content/imagens/chef.jpg" width="100%" height="100%" />
        </div>
        <div class="segunda">
            @using (Html.BeginForm())
            {

                @Html.AntiForgeryToken()


                @Html.LabelFor(model => model.nome, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.nome, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })

                @Html.LabelFor(model => model.cpf, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.cpf, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })

                @Html.LabelFor(model => model.dataNascimento, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.dataNascimento, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })



                @Html.LabelFor(model => model.sexo, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.sexo, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })

                @Html.LabelFor(model => model.idCargo, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.idCargo, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })

                @Html.ActionLink("Voltar", "Index")

                @section Scripts {
                    @Scripts.Render("~/bundles/jqueryval")
                }

            }
        </div>
    </div>
</div>

AppLogin/AppLogin/Areas/RH/Views/Funcionario/Edit.cshtml
@model RestauranteMexicano.Areas.RH.Models.Funcionario

@{
    ViewBag.Title = "Edit";
}

<div class="animated animatedFadeInUp fadeInUp">
    <div class="tabela">
        <br>
        <div class="primeira">
            <!-- <a href='https://www.freepik.com/vectors/food'>Food vector created by freepik - www.freepik.com</a> -->
            <img src="~/Content/imagens/chef.jpg" width="100%" height="100%" />
        </div>
        <div class="segunda">
            @using (Html.BeginForm())
            {

                @Html.AntiForgeryToken()


                @Html.LabelFor(model => model.nome, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.nome, new { htmlAttributes = new { @class = "form-control" } })

                @Html.LabelFor(model => model.cpf, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.cpf, new { htmlAttributes = new { @class = "form-control" } })

                @Html.LabelFor(model => model.dataNascimento, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.dataNascimento, new { htmlAttributes = new { @class = "form-control" } })



                @Html.LabelFor(model => model.sexo, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.sexo, new { htmlAttributes = new { @class = "form-control" } })

                @Html.LabelFor(model => model.idCargo, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.idCargo, new { htmlAttributes = new { @class = "form-control" } })


                <input type="submit" value="Atualizar" class="button" function />

                @Html.ActionLink("Visualizar todos", "Index")

                @section Scripts {
                    @Scripts.Render("~/bundles/jqueryval")
                }

            }
        </div>
    </div>
</div>

AppLogin/AppLogin/Areas/RH/Views/Funcionario/Index.cshtml
@model IEnumerable<RestauranteMexicano.Areas.RH.Models.Funcionario>

@{
    ViewBag.Title = "Index";
}
<div class="animated animatedFadeInUp fadeInUp">
    <table class="tabela">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.cpf)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.dataNascimento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.sexo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.idCargo)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cpf)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dataNascimento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.sexo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.idCargo)
            </td>
            <td class="menu">
                <a href="@Url.Action("Edit", "Funcionario", new { id = item.id})" style="padding:3px;">
                    <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-pencil" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z" />
                    </svg>
                </a>

                <a href="@Url.Action("Details", "Funcionario", new { id = item.id})" style="padding:3px;">
                    <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-info" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path d="M8.93 6.588l-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588z" />
                        <circle cx="8" cy="4.5" r="1" />
                    </svg>
                </a>

                <a href="@Url.Action("Delete", "Funcionario", new { id = item.id})" style="padding:3px;">
                    <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-dash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M4 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 4 8z" />
                    </svg>
                </a>
            </td>
        </tr>
            <tr></tr>
            <tr></tr>
            <tr></tr>
            <tr></tr>
        }
    </table>
</div>

<a href="@Url.Action("Create", "Funcionario", null)" style="padding:3px;">
    <div class="buttonADD"
    </div>
    <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-person-plus-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm7.5-3a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z" />
    </svg>
</a>