AppLogin/AppLogin/Areas/Vendas/Models/Pagamento.cs
using MySql.Data.MySqlClient;
using RestauranteMexicano.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace RestauranteMexicano.Areas.Vendas.Models
{
    public class Pagamento
    {
        public DefaultConnectionDB db = new DefaultConnectionDB();

        /*
            Table: pagamento

            Columns:
            id int AI PK 
            idComanda int 
            formaPagamento varchar(30)
         */

        // Atributos

        [Key]
        [Display(Name = "Id")]
        public int id { get; set; }

        [Required]
        [Display(Name = "Comanda")]
        public int idComanda { get; set; }
        public virtual Comanda comanda { get; set; }

        [Required]
        [Display(Name = "Forma de pagamento")]
        public String formaPagamento { get; set; }

        // Métodos

        public void InsertPagamento(Pagamento pagamento)
        {
            string strQuery = string.Format("insert into Pagamento(id, idComanda, formaPagamento) " +
                                         "values ({0},{1},'{2}');", pagamento.id, pagamento.idComanda, pagamento.formaPagamento);

            db.ExecutaComando(strQuery);
        }

        public List<Pagamento> SelectPagamento()
        {
            string StrQuery = "select * from Pagamento;";
            MySqlDataReader myReader = db.RetornaRegistro(StrQuery);
            var ListaPagamento = new List<Pagamento>();

            while (myReader.Read())
            {
                var objPagamento = new Pagamento()
                {
                    id = int.Parse(myReader["id"].ToString()),
                    idComanda = int.Parse(myReader["idComanda"].ToString()),
                    formaPagamento = myReader["formaPagamento"].ToString()
                };
                ListaPagamento.Add(objPagamento);
            }
            myReader.Close();
            return ListaPagamento;
        }

        public void DeletePagamento(Pagamento pagamento)
        {
            string StrQuery = string.Format("delete from Pagamento where id = {0};", pagamento.id);
            db.ExecutaComando(StrQuery);
        }

        public Pagamento SelectIdPagamento(Pagamento pagamento)
        {
            string StrQuery = string.Format("select * from Pagamento where id = {0};", pagamento.id);
            MySqlDataReader myReader = db.RetornaRegistro(StrQuery);

            var objPagamento = new Pagamento();

            while (myReader.Read())
            {
                objPagamento.id = int.Parse(myReader["id"].ToString());
                objPagamento.idComanda = int.Parse(myReader["idComanda"].ToString());
                objPagamento.formaPagamento = myReader["id"].ToString();
            }
            myReader.Close();
            return objPagamento;
        }
    }
}

AppLogin/AppLogin/Areas/Vendas/Controllers/PagamentoController.cs
using RestauranteMexicano.Areas.Vendas.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RestauranteMexicano.Areas.Vendas.Controllers
{
    public class PagamentoController : Controller
    {
        // GET: Vendas/Pagamento
        public ActionResult Index()
        {
            var objPagamento = new Pagamento();
            var ListaPagamento = objPagamento.SelectPagamento();
            return View(ListaPagamento);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Pagamento pagamento)
        {
            if (ModelState.IsValid)
            {
                var objPagamento = new Pagamento();
                objPagamento.InsertPagamento(pagamento);
                return RedirectToAction("Index");
            }
            return View(pagamento);
        }

        public ActionResult Delete(int id)
        {
            var pagamento = new Pagamento() { id = id };
            var objPagamento = new Pagamento();
            pagamento = objPagamento.SelectIdPagamento(pagamento);
            return View(pagamento);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirma(int id)
        {
            var pagamento = new Pagamento() { id = id };
            var objPagamento = new Pagamento();
            objPagamento.DeletePagamento(pagamento);
            return RedirectToAction("index");
        }
    }
}

AppLogin/AppLogin/Areas/Vendas/Views/Pagamento/Create.cshtml
@model RestauranteMexicano.Areas.Vendas.Models.Pagamento

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="animated animatedFadeInUp fadeInUp">
    <div class="tabela">
        <br>
        <div class="primeira">
            <img src="~/Content/imagens/creditCard.png" width="100%" height="100%" />
        </div>
        <div class="segunda">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                @Html.LabelFor(model => model.idComanda, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.idComanda, new { htmlAttributes = new { @class = "form-control" } })

                @Html.LabelFor(model => model.formaPagamento, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.formaPagamento, new { htmlAttributes = new { @class = "form-control" } })

                <input type="submit" value="Cadastrar" class="button" function />

                @Html.ActionLink("Visualizar todos", "Index")

                @section Scripts {
                    @Scripts.Render("~/bundles/jqueryval")
                }

            }
        </div>
    </div>
</div>

AppLogin/AppLogin/Areas/Vendas/Views/Pagamento/Delete.cshtml
@model RestauranteMexicano.Areas.Vendas.Models.Pagamento

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="animated animatedFadeInUp fadeInUp">
    <div class="tabela">
        <br>
        <div class="primeira">
            <img src="~/Content/imagens/delete-confirmation.png" width="100%" height="100%" />
        </div>
        <div class="segunda">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <h3> Você realmente deseja deletar esse registro? </h3>
                <br />
                <input type="submit" value="Deletar" class="button" />

                @Html.ActionLink("Voltar", "Index")
            }
        </div>
    </div>
</div>

AppLogin/AppLogin/Areas/Vendas/Views/Pagamento/Index.cshtml
@model IEnumerable<RestauranteMexicano.Areas.Vendas.Models.Pagamento>

@{
    ViewBag.Title = "Comandas quitadas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="animated animatedFadeInUp fadeInUp">
    <table class="tabela">
        <tr>
            <th colspan="3">
                <h2>@ViewBag.title</h2>
            </th>
        </tr>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.idComanda)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.formaPagamento)
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.idComanda)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.formaPagamento)
                </td>
                <td class="menu">
                    <a href="@Url.Action("Delete", "Pagamento", new { id = item.id})" style="padding:3px;">
                        <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-dash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M4 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 4 8z" />
                        </svg>
                    </a>
                </td>
            </tr>
        }

    </table>
</div>
<a href="@Url.Action("Create", "Pagamento", null)" style="padding:3px;">
    <div class="buttonADD"
    </div>
    <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-plus" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z" />
    </svg>
</a>