AppLogin/AppLogin/Areas/Vendas/Models/ItensDelivery.cs
using MySql.Data.MySqlClient;
using RestauranteMexicano.Areas.ADM.Models;
using RestauranteMexicano.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace RestauranteMexicano.Areas.Vendas.Models
{
    public class ItensDelivery
    {
        public DefaultConnectionDB db = new DefaultConnectionDB();

        /*
            Table: itensdelivery

            Columns:
            id int AI PK 
            idDelivery int 
            idProduto int 
            valorUnitario decimal(6,2) 
            quantidade int 
            subtotal decimal(6,2)
             
        */

        [Display(Name = "Id")]
        public int id { get; set; }

        [Display(Name = "Id Delivery")]
        public int idDelivery { get; set; }
        public virtual Delivery Delivery { get; set; }

        [Display(Name = "Id Produto")]
        public int idProduto { get; set; }
        public virtual Produto produto { get; set; }

        [Display(Name = "Valor unitário")]
        public decimal valorUnitario { get; set; }

        [Display(Name = "Quantidade")]
        public int quantidade { get; set; }

        [Display(Name = "Subtotal")]
        public decimal subtotal { get; set; }

        public ItensDelivery SelectIdItens(int id)
        {
            string StrQuery = string.Format("select * from itensDelivery where idPedido = {0};", id);
            MySqlDataReader myReader = db.RetornaRegistro(StrQuery);

            var objItens = new ItensDelivery();

            while (myReader.Read())
            {
                objItens.id = int.Parse(myReader["id"].ToString());
                objItens.idDelivery = int.Parse(myReader["idPedido"].ToString());
                objItens.idProduto = int.Parse(myReader["idProduto"].ToString());
                objItens.valorUnitario = decimal.Parse(myReader["valorUnitario"].ToString());
                objItens.quantidade = int.Parse(myReader["quantidade"].ToString());
                objItens.subtotal = decimal.Parse(myReader["subtotal"].ToString());
            }
            myReader.Close();
            return objItens;
        }

        public void InsertItensDelivery(ItensDelivery itensdelivery)
        {
            string valorUnitario = ValorUnitario(itensdelivery);
            string subtotal = Subtotal(itensdelivery);

            string strQuery = string.Format("insert into itensDelivery(id, idDelivery, idProduto, valorUnitario, quantidade, subtotal) " +
                                         "values ({0},{1},{2},{3},{4},{5});", itensdelivery.id, itensdelivery.idDelivery, itensdelivery.idProduto, valorUnitario, itensdelivery.quantidade, subtotal);

            db.ExecutaComando(strQuery);
        }

        public List<ItensDelivery> SelectItensDelivery()
        {
            string StrQuery = "select * from itensDelivery;";
            MySqlDataReader myReader = db.RetornaRegistro(StrQuery);
            var ListaItensDelivery = new List<ItensDelivery>();

            while (myReader.Read())
            {
                var objItensDelivery = new ItensDelivery()
                {
                    id = int.Parse(myReader["id"].ToString()),
                    idDelivery = int.Parse(myReader["idDelivery"].ToString()),
                    idProduto = int.Parse(myReader["idProduto"].ToString()),
                    valorUnitario = decimal.Parse(myReader["valorUnitario"].ToString()),
                    quantidade = int.Parse(myReader["quantidade"].ToString()),
                    subtotal = decimal.Parse(myReader["subtotal"].ToString()),
                };
                ListaItensDelivery.Add(objItensDelivery);
            }
            myReader.Close();
            return ListaItensDelivery;
        }

        public void DeleteItensDelivery(ItensDelivery itensdelivery)
        {
            string StrQuery = string.Format("delete from itensDelivery where id = {0};", itensdelivery.id);
            db.ExecutaComando(StrQuery);
        }

        public ItensDelivery SelectIdItensDelivery(ItensDelivery itensdelivery)
        {
            string StrQuery = string.Format("select * from itensDelivery where id = {0};", itensdelivery.id);
            MySqlDataReader myReader = db.RetornaRegistro(StrQuery);

            var objItensDelivery = new ItensDelivery();

            while (myReader.Read())
            {
                objItensDelivery.id = int.Parse(myReader["id"].ToString());
                objItensDelivery.idDelivery = int.Parse(myReader["idDelivery"].ToString());
                objItensDelivery.idProduto = int.Parse(myReader["idProduto"].ToString());
                objItensDelivery.valorUnitario = decimal.Parse(myReader["valorUnitario"].ToString());
                objItensDelivery.quantidade = int.Parse(myReader["quantidade"].ToString());
                objItensDelivery.subtotal = decimal.Parse(myReader["subtotal"].ToString());

            }
            myReader.Close();
            return objItensDelivery;
        }

        public void UpdateItensDelivery(ItensDelivery itensdelivery)
        {
            string comando = string.Format("select valor from Produto where id = {0};", itensdelivery.idProduto);
            itensdelivery.valorUnitario = decimal.Parse(db.RetornaDado(comando));
            string subtotal = Subtotal(itensdelivery);

            string StrQuery = "";
            StrQuery += "update itensDelivery set ";
            StrQuery += string.Format("idDelivery = {0}, ", itensdelivery.idDelivery);
            StrQuery += string.Format("idProduto = {0}, ", itensdelivery.idProduto);
            StrQuery += string.Format("quantidade = {0}, ", itensdelivery.quantidade);
            StrQuery += string.Format("subtotal = {0} ", subtotal);
            StrQuery += string.Format("where id = {0};", itensdelivery.id);

            db.ExecutaComando(StrQuery);
        }

        public string ValorUnitario(ItensDelivery itensdelivery)
        {
            string comando = string.Format("select valor from Produto where id = {0};", itensdelivery.idProduto);
            itensdelivery.valorUnitario = decimal.Parse(db.RetornaDado(comando));

            var ItenValorUnitario = itensdelivery.valorUnitario.ToString();
            ItenValorUnitario = ItenValorUnitario.Replace(",", ".");

            return ItenValorUnitario;
        }

        public string Subtotal(ItensDelivery itensdelivery)
        {
            itensdelivery.subtotal = itensdelivery.valorUnitario * itensdelivery.quantidade;

            var Itensubtotal = itensdelivery.subtotal.ToString();
            Itensubtotal = Itensubtotal.Replace(",", ".");

            return Itensubtotal;
        }

        public void Atualizar(ItensDelivery itensdelivery)
        {
            string comando = string.Format("select sum(subtotal) from itensDelivery where idDelivery = {0};", itensdelivery.idDelivery);
            var NovoTotal = db.RetornaDado(comando).ToString();
            NovoTotal = NovoTotal.Replace(",", ".");

            string update = "";
            update += "update Delivery set ";
            update += string.Format("total = {0} ", NovoTotal);
            update += string.Format("where id = {0};", itensdelivery.idDelivery);

            db.ExecutaComando(update);

        }
    }
}

AppLogin/AppLogin/Areas/Vendas/Controllers/ItensDeliveryController.cs
using RestauranteMexicano.Areas.Vendas.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RestauranteMexicano.Areas.Vendas.Controllersitensdelivery
{
    public class ItensDeliveryController : Controller
    {
        // GET: Vendas/ItensDelivery
        public ActionResult Index()
        {
            var objitensdelivery = new ItensDelivery();
            var listaitensdelivery = objitensdelivery.SelectItensDelivery();
            return View(listaitensdelivery);
        }

        public ActionResult AdicionarItens()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AdicionarItens(ItensDelivery itensdelivery)
        {
            if (ModelState.IsValid)
            {
                var objitensdelivery = new ItensDelivery();
                objitensdelivery.InsertItensDelivery(itensdelivery);
                objitensdelivery.Atualizar(itensdelivery);
                return RedirectToAction("Index");
            }
            return View(itensdelivery);
        }

        public ActionResult Edit(int id)
        {
            var itensdelivery = new ItensDelivery() { id = id };
            var objitensdelivery = new ItensDelivery();
            itensdelivery = objitensdelivery.SelectIdItensDelivery(itensdelivery);
            return View(itensdelivery);
        }

        [HttpPost]
        public ActionResult Edit(ItensDelivery itensDelivery)
        {
            if (ModelState.IsValid)
            {
                var objitensDelivery = new ItensDelivery();
                objitensDelivery.UpdateItensDelivery(itensDelivery);
                objitensDelivery.Atualizar(itensDelivery);
                return RedirectToAction("Index");
            }
            return View(itensDelivery);
        }

        public ActionResult Delete(int id)
        {
            var itensdelivery = new ItensDelivery() { id = id };
            var objitensdelivery = new ItensDelivery();
            itensdelivery = objitensdelivery.SelectIdItensDelivery(itensdelivery);
            return View(itensdelivery);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirma(int id)
        {
            var itensdelivery = new ItensDelivery() { id = id };
            var objitensdelivery = new ItensDelivery();
            objitensdelivery.DeleteItensDelivery(itensdelivery);
            return RedirectToAction("index");
        }
    }
}

AppLogin/AppLogin/Areas/Vendas/Views/ItensDelivery/AdicionarItens.cshtml
@model RestauranteMexicano.Areas.Vendas.Models.ItensDelivery

@{
    ViewBag.Title = "AdicionarItens";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="animated animatedFadeInUp fadeInUp">
    <div class="tabela">
        <br>
        <div class="primeira">
            <img src="~/Content/imagens/delivery.png" width="100%" height="100%" />
        </div>
        <div class="segunda">
            <h2>Adicione um item para o pedido</h2>
            <br /><br />
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                @Html.LabelFor(model => model.idDelivery, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.idDelivery, new { htmlAttributes = new { @class = "form-control" } })

                @Html.LabelFor(model => model.idProduto, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.idProduto, new { htmlAttributes = new { @class = "form-control" } })

                @Html.LabelFor(model => model.quantidade, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.quantidade, new { htmlAttributes = new { @class = "form-control" } })

                <input type="submit" value="Atualizar" class="button" function />

                @Html.ActionLink("Visualizar todos", "Index")

                @section Scripts {
                    @Scripts.Render("~/bundles/jqueryval")
                }

            }
        </div>
    </div>
</div>

AppLogin/AppLogin/Areas/Vendas/Views/ItensDelivery/Delete.cshtml
@model RestauranteMexicano.Areas.Vendas.Models.ItensDelivery

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="animated animatedFadeInUp fadeInUp">
    <div class="tabela">
        <br>
        <div class="primeira">
            <img src="~/Content/imagens/delete-confirmation.png" width="100%" height="100%" />
        </div>
        <div class="segunda">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <h3> Você realmente deseja deletar esse registro? </h3>
                <br />
                <input type="submit" value="Deletar" class="button" />

                @Html.ActionLink("Voltar", "Index")
            }
        </div>
    </div>
</div>

AppLogin/AppLogin/Areas/Vendas/Views/ItensDelivery/Edit.cshtml
@model RestauranteMexicano.Areas.Vendas.Models.ItensDelivery

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="animated animatedFadeInUp fadeInUp">
    <div class="tabela">
        <br>
        <div class="primeira">
            <img src="~/Content/imagens/delivery.png" width="100%" height="100%" />
        </div>
        <div class="segunda">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                @Html.LabelFor(model => model.idDelivery, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.idDelivery, new { htmlAttributes = new { @class = "form-control" } })

                @Html.LabelFor(model => model.idProduto, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.idProduto, new { htmlAttributes = new { @class = "form-control", disabled = "disabled", @readonly = "readonly" } })

                @Html.LabelFor(model => model.quantidade, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.quantidade, new { htmlAttributes = new { @class = "form-control" } })

                <input type="submit" value="Atualizar" class="button" function />

                @Html.ActionLink("Visualizar todos", "Index")

                @section Scripts {
                    @Scripts.Render("~/bundles/jqueryval")
                }

            }
        </div>
    </div>
</div>

AppLogin/AppLogin/Areas/Vendas/Views/ItensDelivery/Index.cshtml
@model IEnumerable<RestauranteMexicano.Areas.Vendas.Models.ItensDelivery>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="animated animatedFadeInUp fadeInUp">
    <table class="tabela" style="width:970px; margin-top:200px; margin-bottom: 200px;">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.idDelivery)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.idProduto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.valorUnitario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.quantidade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.subtotal)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.idDelivery)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.idProduto)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.valorUnitario)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.quantidade)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.subtotal)
                </td>
                <td class="menu">
                    <a href="@Url.Action("Edit", "ItensDelivery", new { id = item.id})" style="padding:3px;">
                        <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-pencil" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z" />
                        </svg>
                    </a>

                    <a href="@Url.Action("Delete", "ItensDelivery", new { id = item.id})" style="padding:3px;">
                        <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-dash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M4 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 4 8z" />
                        </svg>
                    </a>
                </td>
            </tr>
            <tr></tr>
            <tr></tr>
            <tr></tr>
        }

    </table>
</div>

<a href="@Url.Action("AdicionarItens", "ItensDelivery", null)">
    <div class="buttonADD" style="margin-left:80px;">
        <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-plus" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z" />
        </svg>
    </div>
</a>
<a href="@Url.Action("Index", "Delivery", null)">
    <div class="buttonADD" style="margin-top:100px; margin-left:80px;">
        <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-arrow-left" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z" />
        </svg>
    </div>
</a>