AppLogin/AppLogin/Areas/ADM/Models/Relatorio.cs
using MySql.Data.MySqlClient;
using RestauranteMexicano.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace RestauranteMexicano.Areas.ADM.Models
{
    public class Relatorio
    {
        public DefaultConnectionDB db = new DefaultConnectionDB();

        /* TABELA
        
            id int AI PK 
            dataRelatorio date 
            autor varchar(50) 
            departamento varchar(30) 
            titulo varchar(90) 
            corpo longtext
        */

        // Atributos

        [Key]
        [Display(Name = "Id")]
        public int id { get; set; }

        [Required]
        [Display(Name = "Data")]
        public DateTime dataRelatorio { get; set; }

        [Required]
        [Display(Name = "Autor(a)")]
        [StringLength(50, ErrorMessage = "O limite é de 50 caracteres.")]
        public String autor { get; set; }

        [Required]
        [Display(Name = "Departamento")]
        [StringLength(30, ErrorMessage = "O limite é de 30 caracteres.")]
        public String departamento { get; set; }

        [Required]
        [Display(Name = "Titulo")]
        [StringLength(90, ErrorMessage = "O limite é de 90 caracteres.")]
        public String titulo { get; set; }

        [Required]
        [Display(Name = "Corpo")]
        public String corpo { get; set; }


        // Métodos

        public void InsertRelatorio(Relatorio relatorio)
        {
            string strQuery = string.Format("insert into Relatorio(id, dataRelatorio, autor, departamento, titulo, corpo) " +
                                         "values ({0},'{1}','{2}','{3}','{4}','{5}');", relatorio.id, relatorio.dataRelatorio.ToString("yyyy-MM-dd"), relatorio.autor, relatorio.departamento, relatorio.titulo, relatorio.corpo);

            db.ExecutaComando(strQuery);
        }

        public List<Relatorio> SelectRelatorio()
        {
            string StrQuery = "select * from Relatorio;";
            MySqlDataReader myReader = db.RetornaRegistro(StrQuery);
            var ListaRelatorio = new List<Relatorio>();

            while (myReader.Read())
            {
                var objRelatorio = new Relatorio()
                {
                    id = int.Parse(myReader["id"].ToString()),
                    dataRelatorio = DateTime.Parse(myReader["dataRelatorio"].ToString()),
                    autor = myReader["autor"].ToString(),
                    departamento = myReader["departamento"].ToString(),
                    titulo = myReader["titulo"].ToString(),
                    corpo = myReader["corpo"].ToString()
                };
                ListaRelatorio.Add(objRelatorio);
            }
            myReader.Close();
            return ListaRelatorio;
        }

        public void DeleteRelatorio(Relatorio relatorio)
        {
            string StrQuery = string.Format("delete from Relatorio where id = {0};", relatorio.id);
            db.ExecutaComando(StrQuery);
        }

        public Relatorio SelectIdRelatorio(Relatorio relatorio)
        {
            string StrQuery = string.Format("select * from Relatorio where id = {0};", relatorio.id);
            MySqlDataReader myReader = db.RetornaRegistro(StrQuery);

            var objRelatorio = new Relatorio();

            while (myReader.Read())
            {
                objRelatorio.dataRelatorio = DateTime.Parse(myReader["dataRelatorio"].ToString());
                objRelatorio.autor = myReader["autor"].ToString();
                objRelatorio.departamento = myReader["departamento"].ToString();
                objRelatorio.titulo = myReader["titulo"].ToString();
                objRelatorio.corpo = myReader["corpo"].ToString();
            }
            myReader.Close();
            return objRelatorio;
        }

        public void UpdateRelatorio(Relatorio relatorio)
        {
            string StrQuery = "";
            StrQuery += "update Relatorio set ";
            StrQuery += string.Format("dataRelatorio = '{0}', ", relatorio.dataRelatorio.ToString("yyyy-MM-dd"));
            StrQuery += string.Format("autor = '{0}', ", relatorio.autor);
            StrQuery += string.Format("departamento = '{0}', ", relatorio.departamento);
            StrQuery += string.Format("titulo = '{0}', ", relatorio.titulo);
            StrQuery += string.Format("corpo = '{0}' ", relatorio.corpo);
            StrQuery += string.Format("where id = {0};", relatorio.id);

            db.ExecutaComando(StrQuery);
        }
    }
}

AppLogin/AppLogin/Areas/ADM/Controllers/RelatorioController.cs
using RestauranteMexicano.Areas.ADM.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RestauranteMexicano.Areas.ADM.Controllers
{
    public class RelatorioController : Controller
    {
        // GET: ADM/Relatorio
        public ActionResult Index()
        {
            var objRelatorio = new Relatorio();
            var ListaRelatorio = objRelatorio.SelectRelatorio();
            return View(ListaRelatorio);
        }

        public ActionResult Details(int id)
        {
            Relatorio relatorio = new Relatorio() { id = id };
            var objRelatorio = new Relatorio();
            relatorio = objRelatorio.SelectIdRelatorio(relatorio);
            return View(relatorio);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Relatorio relatorio)
        {
            if (ModelState.IsValid)
            {
                var objRelatorio = new Relatorio();
                objRelatorio.InsertRelatorio(relatorio);
                return RedirectToAction("Index");
            }
            return View(relatorio);
        }

        public ActionResult Edit(int id)
        {
            var relatorio = new Relatorio() { id = id };
            var objRelatorio = new Relatorio();
            relatorio = objRelatorio.SelectIdRelatorio(relatorio);
            return View(relatorio);
        }

        [HttpPost]
        public ActionResult Edit(Relatorio relatorio)
        {
            if (ModelState.IsValid)
            {
                var objRelatorio = new Relatorio();
                objRelatorio.UpdateRelatorio(relatorio);
                return RedirectToAction("Index");
            }
            return View(relatorio);
        }

        public ActionResult Delete(int id)
        {
            var relatorio = new Relatorio() { id = id };
            var objRelatorio = new Relatorio();
            relatorio = objRelatorio.SelectIdRelatorio(relatorio);
            return View(relatorio);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirma(int id)
        {
            var relatorio = new Relatorio() { id = id };
            var objRelatorio = new Relatorio();
            objRelatorio.DeleteRelatorio(relatorio);
            return RedirectToAction("index");
        }
    }
}

AppLogin/AppLogin/Areas/ADM/Views/Relatorio/Create.cshtml
@model RestauranteMexicano.Areas.ADM.Models.Relatorio

@{
    ViewBag.Title = "Create";
}

<div class="animated animatedFadeInUp fadeInUp">
    <div class="tabela">
        <br>
        <div class="primeira">
            <img src="~/Content/imagens/relatorio.SVG" width="100%" height="100%" />
        </div>
        <div class="segunda">
            @using (Html.BeginForm())
             {
                @Html.AntiForgeryToken()
         
                @Html.LabelFor(model => model.dataRelatorio, htmlAttributes: new { @class = "control-label col-md-2" })          
                @Html.EditorFor(model => model.dataRelatorio, new { htmlAttributes = new { @class = "form-control" } })
         
                @Html.LabelFor(model => model.autor, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.autor, new { htmlAttributes = new { @class = "form-control" } })
                       
                @Html.LabelFor(model => model.departamento, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.departamento, new { htmlAttributes = new { @class = "form-control" } })
        
                @Html.LabelFor(model => model.titulo, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.titulo, new { htmlAttributes = new { @class = "form-control" } })
            
                @Html.LabelFor(model => model.corpo, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.corpo, new { htmlAttributes = new { @class = "form-control" } })

                <input type="submit" value="Cadastrar" class="button" function />

                @Html.ActionLink("Visualizar todos", "Index")

                @section Scripts {
                    @Scripts.Render("~/bundles/jqueryval")
                }

             }
        </div>
    </div>
</div>

AppLogin/AppLogin/Areas/ADM/Views/Relatorio/Delete.cshtml
@model RestauranteMexicano.Areas.ADM.Models.Relatorio

@{
    ViewBag.Title = "Delete";
}

<div class="animated animatedFadeInUp fadeInUp">
    <div class="tabela">
        <br>
        <div class="primeira">
            <img src="~/Content/imagens/delete-confirmation.png" width="100%" height="100%" />
        </div>
        <div class="segunda">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <h3> Você realmente deseja deletar esse registro? </h3>
                <br />
                <input type="submit" value="Deletar" class="button" />

                @Html.ActionLink("Voltar", "Index")
            }
        </div>
    </div>
</div>

AppLogin/AppLogin/Areas/ADM/Views/Relatorio/Details.cshtml
@model RestauranteMexicano.Areas.ADM.Models.Relatorio

@{
    ViewBag.Title = "Details";
}

<div class="animated animatedFadeInUp fadeInUp">
    <div class="tabela">
        <br>
        <div class="primeira">
            <img src="~/Content/imagens/relatorio.svg" width="100%" height="100%" />
        </div>
        <div class="segunda">
            @using (Html.BeginForm())
            {

                @Html.LabelFor(model => model.dataRelatorio, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.dataRelatorio, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })

                @Html.LabelFor(model => model.autor, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.autor, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })

                @Html.LabelFor(model => model.departamento, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.departamento, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })

                @Html.LabelFor(model => model.titulo, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.titulo, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })

                @Html.LabelFor(model => model.corpo, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.corpo, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
               
                @Html.ActionLink("Voltar", "Index")

                @section Scripts {
                    @Scripts.Render("~/bundles/jqueryval")
                }

            }
        </div>
    </div>
</div>

AppLogin/AppLogin/Areas/ADM/Views/Relatorio/Edit.cshtml
@model RestauranteMexicano.Areas.ADM.Models.Relatorio

@{
    ViewBag.Title = "Edit";
}

<div class="animated animatedFadeInUp fadeInUp">
    <div class="tabela">
        <br>
        <div class="primeira">
            <img src="~/Content/imagens/relatorio.svg" width="100%" height="100%" />
        </div>
        <div class="segunda">
            @using (Html.BeginForm())
            {

                @Html.HiddenFor(model => model.id)


                @Html.LabelFor(model => model.dataRelatorio, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.dataRelatorio, new { htmlAttributes = new { @class = "form-control" } })

                @Html.LabelFor(model => model.autor, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.autor, new { htmlAttributes = new { @class = "form-control" } })

                @Html.LabelFor(model => model.departamento, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.departamento, new { htmlAttributes = new { @class = "form-control" } })

                @Html.LabelFor(model => model.titulo, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.titulo, new { htmlAttributes = new { @class = "form-control" } })

                @Html.LabelFor(model => model.corpo, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.corpo, new { htmlAttributes = new { @class = "form-control" } })

                <input type="submit" value="Atualizar" class="button" function />

                @Html.ActionLink("Visualizar todos", "Index")

                @section Scripts {
                    @Scripts.Render("~/bundles/jqueryval")
                }

            }
        </div>
    </div>
</div>

AppLogin/AppLogin/Areas/ADM/Views/Relatorio/Index.cshtml
@model IEnumerable<RestauranteMexicano.Areas.ADM.Models.Relatorio>

@{
    ViewBag.Title = "Index";
}

<div class="animated animatedFadeInUp fadeInUp">
    <table class="tabela">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.dataRelatorio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.autor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.departamento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.titulo)
            </th>
            <th></th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.dataRelatorio)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.autor)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.departamento)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.titulo)
                </td>
                <td class="menu">
                    <a href="@Url.Action("Edit", "Relatorio", new { id = item.id})" style="padding:3px;">
                        <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-pencil" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z" />
                        </svg>
                    </a>

                    <a href="@Url.Action("Details", "Relatorio", new { id = item.id})" style="padding:3px;">
                        <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-info" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path d="M8.93 6.588l-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588z" />
                            <circle cx="8" cy="4.5" r="1" />
                        </svg>
                    </a>

                    <a href="@Url.Action("Delete", "Relatorio", new { id = item.id})" style="padding:3px;">
                        <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-dash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M4 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 4 8z" />
                        </svg>
                    </a>
                </td>
            </tr>
            <tr></tr><tr></tr><tr></tr>
        }

    </table>
</div>

<a href="@Url.Action("Create", "Relatorio", null)" style="padding:3px;">
    <div class="buttonADD"
    </div>
    <svg width="2em" height="2em" viewBox="0 0 16 16" class="bi bi-plus" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z" />
    </svg>
</a>